FROM gitpod/workspace-full:latest

USER root
# Install custom tools, runtime, etc.
RUN apt-get update && apt-get install -y \

get install git build-essential autoconf libsndfile1-dev libliquid-dev mc

RUN ./autogen.sh && ./configure && make

RUN make install

USER gitpod
# Apply user-specific settings
# ENV ...

# Give back control
USER root
